/**
 * Generates the installer's game list from the built-in profiles.
 *
 * Two things come out of this, both derived from the same profiles the bridge
 * itself uses, so a new game means adding one JSON file and nothing else:
 *
 *  - a [Tasks] entry per game, so the wizard offers it as a checkbox
 *  - a host -> task lookup built from each game's allowedOrigins, so the
 *    wizard can tick the game whose site you downloaded from
 *
 * Hand-maintaining either would mean the installer drifting from the profiles,
 * and a drifted origin shows up as "the wrong game was pre-selected", which
 * nobody reports.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

/** Inno string literals double their single quotes. */
function pas(value) {
  return `'${String(value).replace(/'/g, "''")}'`
}

/** Inno's [Tasks] Description is a plain string; keep quotes out of trouble. */
function iss(value) {
  return String(value).replace(/"/g, "'")
}

export function generateGamesInclude(builtinDir, outFile) {
  const profiles = readdirSync(builtinDir)
    .filter(name => name.endsWith('.json'))
    .sort()
    .map(name => JSON.parse(readFileSync(path.join(builtinDir, name), 'utf8')))

  const tasks = profiles.map(
    profile =>
      `Name: "game_${profile.id}"; Description: "${iss(profile.name)}"; ` +
      `GroupDescription: "Which games should this bridge handle?"; Flags: unchecked`,
  )

  // host -> task. A host, not an origin: the referrer a browser records is the
  // page that linked the download, so it carries a path we do not care about.
  const byHost = new Map()
  const conflicts = []
  for (const profile of profiles) {
    for (const origin of profile.allowedOrigins ?? []) {
      let host
      try {
        host = new URL(origin).host
      } catch {
        continue
      }
      const existing = byHost.get(host)
      if (existing && existing !== profile.id) {
        conflicts.push(`${host} is claimed by both ${existing} and ${profile.id}`)
        continue
      }
      byHost.set(host, profile.id)
    }
  }

  // Two games sharing a host would make the pre-selection a coin toss, and the
  // wrong game being ticked is not something a user would think to report.
  if (conflicts.length > 0) {
    throw new Error(`Cannot generate the installer game list: ${conflicts.join('; ')}`)
  }

  const branches = [...byHost.entries()].map(
    ([host, id], index) =>
      `  ${index === 0 ? 'if' : 'else if'} Host = ${pas(host.toLowerCase())} then Result := ${pas(`game_${id}`)}`,
  )

  // `games add` is idempotent and joins whatever bridge is already configured,
  // so re-running setup to add a game extends the install rather than doubling it.
  const runs = profiles.map(
    profile =>
      `Filename: "{cmd}"; Parameters: "/c ""{app}\\{#MyLauncher}"" games add ${profile.id}"; \\\r\n` +
      `  StatusMsg: "Enabling ${iss(profile.name)}..."; WorkingDir: "{app}"; ` +
      `Flags: runhidden waituntilterminated; Tasks: game_${profile.id}`,
  )

  const lines = [
    '; ==========================================================================',
    ';  GENERATED by installer/windows/generate-games.mjs -- do not edit.',
    ';  Source: src/games/builtin/*.json',
    '; ==========================================================================',
    '',
    '[Tasks]',
    ...tasks,
    '',
    '[Run]',
    ...runs,
    '',
    '[Code]',
    'function TaskForDownloadHost(const Host: String): String;',
    'begin',
    '  Result := ' + pas('') + ';',
    ...(branches.length > 0 ? branches.map((line, i) => (i === branches.length - 1 ? `${line};` : line)) : []),
    'end;',
    '',
    'function AllGameTasks(): String;',
    'begin',
    `  Result := ${pas(profiles.map(p => `game_${p.id}`).join(','))};`,
    'end;',
    '',
  ]

  writeFileSync(outFile, lines.join('\r\n'))
  return { games: profiles.map(p => p.id), hosts: [...byHost.keys()] }
}
